#!/usr/bin/env bash

# enable configuration in sites-enabled using a symbolic link
rm /etc/nginx/sites-enabled/mysite.com
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
